<?php
return [
  // Navbar
  'strHomePage'            => 'Home Page',
  'strRent'                => 'Rent',
  'strSales'               => 'Sale',
  'strProject'             => 'Projects',
  'strNews'                => 'News',
  'strAboutUs'             => 'About Us',
  'strExistsProjects'      => 'Existed Projects',
  'strNewProjects'         => 'New Projects',
  'strUpcomingProjects'    => 'Upcoming Projects',
  'strCommercial'          => 'Commercial',
  // Homepage
  'strNewProperties'       => 'New Properties',
  'strHotProperties'       => 'Hot Properties',
  // Search
  'strSearch'              => 'Search',
  // Properties
  'strCode'                => 'Code',
  'strAsignedAgent'        => 'Agent',
  'strLocation'            => 'Location',
  'strPrice'               => 'Price',
  'strAvailableDate'       => 'Available Date',
  'strUpdatedDate'         => 'Updated Date',
  'strFurnitureFeatures'   => 'Furniture Features',
  'strParticallyFurnished' => 'Partically Furnished',
  'strUnfurnished'         => 'Unfurnished',
  'strDescription'         => 'Description',
  'strAmenities'           => 'Amenities',
  'strAmenitiesInside'     => 'Amenities Inside',
  'strAmenitiesNearby'     => 'Amenities Nearby',
  'strPropertyInformation' => 'Property Information',
  'strName'                => 'Name',
  'strArea'                => 'Area',
  // Project
  'strProjectInformation'  => 'Project Information',
  'strProjectName'         => 'Project Name',
  'strInvestor'            => 'Investor',
  'strAddress'             => 'Address',
  'strSalePrice'           => 'Sale Price',
  'strRentPrice'           => 'Rental',
  'strProjectDescription'  => 'Project Description',
  'strListofProjects'      => 'Project List',
  // Other String
  'strEmail'               => 'Email',
  'strSave'                => 'Save',
  'strPrint'               => 'Print',
  'strName'                => 'Name',
  'strPhone'               => 'Phone',
  'strProfileImage'        => 'Profile Image',
  'strSort'                => 'Sort',
  'strNewest'              => 'Newest',
  'strOldest'              => 'Oldest',
  'strLowestPrice'         => 'Lowest Price',
  'strHighestPrice'        => 'Hgihest Price',
  'strItemsPerPages'       => 'Items Per Page',
  'strSaveToSeeLater'      => 'Save to see later',
  'strViewDetail'          => 'View Detail',
  'strPrevious'            => 'Previous',
  'strNext'                => 'Next',
  'strTitle'               => 'Title',
  // save
  'strSaveTitle'           => 'Saved',
  // search
  'strSearchTitle'         => 'Search Result For Keywords:',
  'strNext'                => 'Next',
  'strNext'                => 'Kế Tiếp',
  'strNext'                => 'Kế Tiếp',
  'strNext'                => 'Kế Tiếp',
];
