<?php
return [
  // Navbar
  'strHomePage'            => 'Trang Chủ',
  'strRent'                => 'Thuê',
  'strSales'               => 'Bán',
  'strProject'             => 'Dự Án',
  'strNews'                => 'Tin Tức',
  'strAboutUs'             => 'Về chúng tôi',
  'strExistsProjects'      => 'Dự Án Hiện Tại',
  'strNewProjects'         => 'Dự Án Mới',
  'strUpcomingProjects'    => 'Dự Án Sắp Tới',
  'strCommercial'          => 'Thương Mại',
  // Homepage
  'strNewProperties'       => 'Mới',
  'strHotProperties'       => 'Hot',
  // Search
  'strSearch'              => 'Tìm Kiếm',
  // Properties
  'strCode'                => 'Mã số',
  'strAsignedAgent'        => 'Người Liên Hệ',
  'strLocation'            => 'Vị trí',
  'strPrice'               => 'Giá',
  'strAvailableDate'       => 'Ngày Sẵn Sàng',
  'strUpdatedDate'         => 'Ngày Cập Nhật',
  'strFurnitureFeatures'   => 'Nội Thất',
  'strParticallyFurnished' => 'Nội Thất Một Phần',
  'strUnfurnished'         => 'Không Bao Gồm Nội Thất ',
  'strDescription'         => 'Mô Tả',
  'strAmenities'           => 'Tiện Nghi',
  'strAmenitiesInside'     => 'Tiện ích nội khu',
  'strAmenitiesNearby'     => 'Tiện Nghi Lân Cận',
  'strPropertyInformation' => 'Tổng Quan',
  'strName'                => 'Tên',
  'strArea'                => 'Diện Tích',
  // Project
  'strProjectInformation'  => 'Thông Tin Dự Án',
  'strProjectName'         => 'Tên Dự Án',
  'strInvestor'            => 'Chủ Đầu Tư',
  'strAddress'             => 'Địa Chỉ',
  'strSalePrice'           => 'Giá Bán',
  'strRentPrice'           => 'Giá Thuê',
  'strProjectDescription'  => 'Mô Tả Dự Án',
  'strListofProjects'      => 'Danh Sách Dự Án',
  // Other String
  'strEmail'               => 'Email',
  'strSave'                => 'Lưu',
  'strPrint'               => 'In',
  'strName'                => 'Tên',
  'strPhone'               => 'Điện Thoại',
  'strProfileImage'        => 'Hình',
  'strSort'                => 'Sắp xếp',
  'strNewest'              => 'Mới Nhất',
  'strOldest'              => 'Lâu Nhất',
  'strLowestPrice'         => 'Giá Thấp Nhất',
  'strHighestPrice'        => 'Giá Cao Nhất',
  'strItemsPerPages'       => 'Số Lượng Trên Trang',
  'strSaveToSeeLater'      => 'Lưu Lại Xem Sau',
  'strViewDetail'          => 'Xem Chi Tiết',
  'strPrevious'            => 'Trở Lại',
  'strNext'                => 'Kế Tiếp',
  'strTitle'               => 'Chức Vụ',
  // save
  'strSaveTitle'           => 'Những Gì Bạn Đã Lưu',
  // search
  'strSearchTitle'         => 'Kết Quả Tìm Kiếm Cho Từ Khóa:',
  'strNext'                => 'Kế Tiếp',
  'strNext'                => 'Kế Tiếp',
  'strNext'                => 'Kế Tiếp',
  'strNext'                => 'Kế Tiếp',
];
